### ISSUE TITLE
 请问$dispatch是什么意思

### ISSUE THREAD

**Issue by princessJoanna** [cycgit/vue-pagination#2]

**Comment by nooldey** [comment]
`使用 $dispatch() 派发事件，事件沿着父链冒泡；`
请详细阅读VUE文档： http://vuejs.org.cn/guide/components.html#自定义事件

**Comment by wuxiaolan91** [comment]
然而这个组件其实并不兼容呀。用了vue2里移除了的事件dispatch。

**Comment by cycgit** [comment]
@wuxiaolan91 嗯 你说的对。 我之前的写法问题很大... 感谢指出🙏
